sudo: required
dist: trusty
language: c

matrix:
  include:
    - compiler: gcc-7
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'gcc-7', 'cmake' ]
      env: COMPILER=gcc-7

    - compiler: clang-3.9
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' , 'llvm-toolchain-3.9' ]
          packages: [ 'clang-3.9', 'cmake']
      env: COMPILER=clang-3.9

before_install:
  - sudo apt-get update -qq

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$COMPILER .. && make
  - ./test/test_plist
  - ./test/test_pstack
  - ./test/test_pqueue
  