# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: c

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://ppa.launchpad.net/george-edison55/precise-backports/ubuntu precise main'
          packages:
            - gcc-6
            - cmake
      env: COMPILER=gcc-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-4.0
            - sourceline: 'deb http://ppa.launchpad.net/george-edison55/precise-backports/ubuntu precise main'
          packages:
            - clang-4.0
            - cmake
      env: COMPILER=clang-4.0

before_install:
  - sudo apt-get update -qq
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$COMPILER .. && make
  - ./test_plist
  - ./test_pstack
  - ./test_pqueue
  