sudo: required
dist: trusty
language: c

matrix:
  include:
    - compiler: gcc-7
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'gcc-7' ]
      env: [COMPILER=gcc-7, CMAKE_C_FLAGS_DEBUG="-std=c11 -Wall -Wextra -Wpedantic -Wchkp -Wuninitialized -Winit-self --coverage -O0", CMAKE_EXE_LINKER_FLAGS=-lgcov]

    - compiler: clang-3.9
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'clang-3.9']
      env: [COMPILER=clang-3.9, CMAKE_C_FLAGS_DEBUG="-std=c11 -Wall -Wextra -Wpedantic -Wuninitialized -Winit-self", CMAKE_EXE_LINKER_FLAGS=]

    - compiler: musl-gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'gcc-7', 'musl-tools', 'musl-dev' ]
      env: [COMPILER=musl-gcc, CMAKE_C_FLAGS_DEBUG="-std=c11 -Wall -Wextra -Wpedantic -Wuninitialized -Winit-self -Wchkp", CMAKE_EXE_LINKER_FLAGS=]

before_install:
  - sudo apt-get update -qq

install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90 || echo "OK"

after_success:
  - bash <(curl -s https://codecov.io/bash) -f '!*unity*' -F unittesting

before_script:

  # Build Folder
  - mkdir build
  - cd build

  # Update / Install CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p external/cmake
      pushd external/cmake
      wget https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.sh
      chmod +x cmake-*-Linux-x86_64.sh
      ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
      export PATH="${PWD}/bin:$PATH"
      popd
    else
      if ! brew ls --version cmake &>/dev/null; then brew update; brew install cmake; fi
    fi

script:
  - cmake -DENABLE_CPPCHECK=ON -DCMAKE_C_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS_DEBUG="$CMAKE_C_FLAGS_DEBUG" -DCMAKE_EXE_LINKER_FLAGS=$CMAKE_EXE_LINKER_FLAGS ..
  - make -j 4
  - make check
  - cd test && ctest -j 4
