sudo: required
dist: trusty
language: c

matrix:
  include:
    - compiler: gcc-7
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'gcc-7', 'cmake' ]
      env: COMPILER=gcc-7

    - compiler: clang-3.9
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'clang-3.9', 'cmake']
      env: COMPILER=clang-3.9

before_install:
  - sudo apt-get update -qq

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. && make VERBOSE=1 -j 4
  - cd test
  - ctest -j 4
  - cd ../..
  