sudo: required
dist: trusty
language: c

matrix:
  include:
    - compiler: gcc-6
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'george-edison55-precise-backports' ]
          packages: [ 'gcc-6', 'cmake', 'cmake-data' ]
      env: COMPILER=gcc-6

    - compiler: clang-3.8
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'george-edison55-precise-backports' , 'llvm-toolchain-precise-3.8' ]
          packages: [ 'clang-3.8', 'cmake', 'cmake-data' ]
      env: COMPILER=clang-3.8

before_install:
  - sudo apt-get update -qq

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$COMPILER .. && make
  - ./test/test_plist
  - ./test/test_pstack
  - ./test/test_pqueue
  